<?php 
/**
 * CoolMS2 Twitter Bootstrap Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/twbs for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsTwbs;

$url = $this->overwriteUrl != '' ? $this->overwriteUrl : $this->url(null, [], [], true);

$parametersAdd = '';
foreach ($this->parameters as $name => $value) {
    $parametersAdd .= '&' . $name . '=' . $value;
}

foreach ($this->exportRenderers as $type => $name):
    $urlExport = $url . '?' . $this->generalParameterNames['rendererType'] . '=' . $type . $parametersAdd;
?>
    <a class="btn btn-default" href="<?= $urlExport; ?>">
        <?= $name; ?>
    </a>
<?php 
endforeach;
