<?php 
/**
 * CoolMS2 Twitter Bootstrap Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/twbs for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsTwbs;

/* @var $action \CmsDatagrid\Action\Mass */
/* @var $paginator \Zend\Paginator\Paginator */

$paginator = $this->paginator;

?>
<!-- Start footer -->
<div class="row-fluid row" id="<?= $this->gridId; ?>_footer">
    <!-- Mass actions -->
    <div class="span4 col-md-4">
    <?php foreach($this->massActions as $action): ?>
        <a href="#" class="btn btn-default massAction" data-url="<?= $action->getLink(); ?>">
            <?= $this->translate($action->getTitle()); ?>
        </a>
    <?php endforeach; ?>
    </div>
    <!-- Pagination -->
    <div class="span4 col-md-4 text-center">
        <input type="hidden" name="<?= $this->parameterNames['currentPage']; ?>" value="<?= $paginator->getPages()->current; ?>">
        <?= $this->paginationControl(
            $paginator,
            'Elastic',
            'cms-twbs/datagrid/paginator',
            [
                'activeParameters' => $this->activeParameters, 
                'parameterNames' => $this->parameterNames,
                'gridId' => $this->gridId
            ]
        ); ?>
    </div>
    <!-- Info -->
    <div class="span4 col-md-4 text-right">
        <?= sprintf(
            $this->translate('Showing %d of %d item(s)'),
            $paginator->getCurrentItemCount(),
            $paginator->getTotalItemCount()
        ); ?><br />
        <?= sprintf(
            $this->translate('Page %d of %d item(s)'),
            $paginator->getCurrentPageNumber(),
            $paginator->count()
        ); ?>
    </div>
</div><!-- End footer -->

<?php $this->inlineScript()->captureStart(); ?>
function <?= $this->gridId; ?>_toggleCheckboxes(element){
    var elements = document.getElementsByName('massActionSelected[]');

    var useThis = element.checked;
    for(i = 0; i < elements.length; i++){
        elements[i].checked = useThis;
    }
}

$(document).ready(function() {
    $('#<?= $this->gridId; ?>_footer a.massAction').click( function() {
        var form = document.createElement('form');
        form.setAttribute('name', 'massAction');
        form.setAttribute('method', 'post');
        form.setAttribute('action', $(this).attr('data-url'));

        var checkboxes = document.getElementsByName('massActionSelected[]');
        for(i = 0; i < checkboxes.length; i++){
            var node = checkboxes[i].cloneNode();
            node.name = '<?= $this->parameterNames['massIds']; ?>[]';
            form.appendChild(node);
        }

        document.body.appendChild(form);
        form.submit();
        document.body.removeChild(form);
    });

    $('#<?= $this->gridId; ?> tr').click(function(event) {
        if (event.target.type !== 'checkbox') {
          $(':checkbox', this).trigger('click');
        }
    });
});
<?php $this->inlineScript()->captureEnd();
