<?php 
/**
 * CoolMS2 Twitter Bootstrap Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/twbs for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsDatagrid;

?>
<div class="row row-fluid" style="margin-bottom: 5px;">
    <!-- Export buttons -->
    <div class="span12 col-md-12 text-right">
        <?= $this->partial('cms-twbs/datagrid/export'); ?>
    </div>
</div>
