<?php 
/**
 * CoolMS2 Address module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsAddress for the canonical source repository
 * @copyright Copyright (c) 2006-2014 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsAddress;

// Set translation and namespace options here
$this->formLabel()->setTranslatorTextDomain(__NAMESPACE__);
$this->formRow()->setTranslatorTextDomain(__NAMESPACE__);
$this->formSelect()->setTranslatorTextDomain(__NAMESPACE__);
$this->formText()->setTranslatorTextDomain(__NAMESPACE__);

$fieldset = $this->fieldset;

$this->render('cms-address/address/fieldset.phtml');

$fieldset->get('houseNumber')->setOptions([
        'twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-4'],
                'formGroup' => ['elements' => ['housing', 'apartmentNumber']],
            ],
        ],
    ]);

$fieldset->get('housing')->setOptions([
        'twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-4'],
            ],
        ],
    ]);

$fieldset->get('apartmentNumber')->setAttributes(['twb' => ['class' => 'form-control']])
    ->setOptions(['twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-4'],
            ],
        ],
        'label_attributes' => ['twb' => ['class' => 'control-label sr-only']],
    ]);

$fieldset->get('changedAt')->setAttributes(['twb' => ['class' => 'form-control']])
    ->setOptions(['twb' => [
            'decorators' => ['col', 'formGroup'],
        ],
        'label_attributes' => ['twb' => ['class' => 'control-label sr-only']]
    ]);

?>
<?= $this->formCollection()->renderElements($fieldset);
